version: '3.8'

services:
  odoo:
    image: odoo:16.0
    ports:
      - "8069:8069"
    environment:
      - HOST=db
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
  odoo-data:

